### ISSUE TITLE
UTC Timestamp in Query

### ISSUE THREAD

**Issue by weilinear** [hczhu/TickerTick-API#5]
Would be great to query by timestamp. For example, those cases in README could have a `(and () before_utc: 1636624740000)` and `(and () after_utc: 1636624740000)`

**Comment by hczhu** [comment]
Thanks for the suggestion.  @weilinear 

`after_utc` is not necessary, since the stories of a feed are already sorted in reverse chronological order.  One can fetch the continuous feed page by page until the oldest story crosses the utc timestamp in `after_utc`.

There is already a parameter [`hours_ago`](https://github.com/hczhu/TickerTick-API#parameters) to do the same as `before _utc` though it uses hours instead of seconds.  Not sure if that `hours_ago` would work for your use case. 

I can definitely add a term `before_utc` later.

**Comment by weilinear** [comment]
Hours before is a bit of an approximation. I wanna to have all news within a time range if possible to back test. One use case, suppose I wanna see what happened exactly before a quote changes w.r.t. prices, then the timing is really important to ensure causality.

**Comment by hczhu** [comment]
Sounds reasonable. I'll add `before_utc` later.
